# sonar-project.properties
sonar.projectKey=225106138_8.2CDevSecOps
sonar.organization=225106138
sonar.host.url=https://sonarcloud.io
sonar.login=${c0e7f434c67cd061f8105fe5d6fb9b55968eed0f}

sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8